<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="minimal_4wheel_ackermann">

  <!-- Units: meters, kilograms, radians -->
  <!-- xacro already defines pi -->

  <!-- Simple dimensions -->
  <xacro:property name="chassis_length" value="0.30"/>
  <xacro:property name="chassis_width"  value="0.20"/>
  <xacro:property name="chassis_height" value="0.08"/>

  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_width"  value="0.02"/>

  <!-- Geometry -->
  <xacro:property name="wheelbase" value="0.22"/>   <!-- distance between front and rear wheel centers -->
  <xacro:property name="track"     value="0.18"/>   <!-- distance between left and right wheel centers -->

  <!-- Place base_link at the chassis COM, at z = wheel_radius + chassis_half_height so wheels touch ground. -->
  <xacro:property name="base_z" value="${wheel_radius + chassis_height/2.0}"/>
  <xacro:property name="wheel_z" value="${wheel_radius - base_z}"/>

  <xacro:macro name="inertial_box" params="mass x y z">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <!-- Solid box inertia -->
      <inertia
        ixx="${mass/12.0 * (y*y + z*z)}"
        iyy="${mass/12.0 * (x*x + z*z)}"
        izz="${mass/12.0 * (x*x + y*y)}"
        ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="inertial_cylinder_y" params="mass radius length">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <!-- Cylinder aligned with Y axis (wheel spin axis). Approximated by swapping principal axes. -->
      <inertia
        ixx="${mass/12.0 * (3*radius*radius + length*length)}"
        iyy="${0.5*mass*radius*radius}"
        izz="${mass/12.0 * (3*radius*radius + length*length)}"
        ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </xacro:macro>

  <!-- Frames -->
  <link name="base_footprint"/>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="Grey">
        <color rgba="0.6 0.6 0.6 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <xacro:inertial_box mass="3.0" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}"/>
  </link>

  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${base_z}" rpy="0 0 0"/>
  </joint>

  <!-- Rear wheels (drive) -->
  <link name="rear_left_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="Black">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder_y mass="0.25" radius="${wheel_radius}" length="${wheel_width}"/>
  </link>

  <joint name="rear_left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rear_left_wheel_link"/>
    <origin xyz="${-wheelbase/2} ${track/2} ${wheel_z}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <link name="rear_right_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="Black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder_y mass="0.25" radius="${wheel_radius}" length="${wheel_width}"/>
  </link>

  <joint name="rear_right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rear_right_wheel_link"/>
    <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_z}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Front steering knuckles -->
  <link name="front_left_steer_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.02"/>
      </geometry>
      <material name="Blue">
        <color rgba="0.2 0.2 0.8 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.02"/>
      </geometry>
    </collision>
    <xacro:inertial_box mass="0.05" x="0.02" y="0.02" z="0.02"/>
  </link>

  <joint name="front_left_steer_joint" type="revolute">
    <parent link="base_link"/>
    <child link="front_left_steer_link"/>
    <origin xyz="${wheelbase/2} ${track/2} ${wheel_z}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.6" upper="0.6" effort="5.0" velocity="2.0"/>
  </joint>

  <link name="front_right_steer_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.02"/>
      </geometry>
      <material name="Blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.02"/>
      </geometry>
    </collision>
    <xacro:inertial_box mass="0.05" x="0.02" y="0.02" z="0.02"/>
  </link>

  <joint name="front_right_steer_joint" type="revolute">
    <parent link="base_link"/>
    <child link="front_right_steer_link"/>
    <origin xyz="${wheelbase/2} ${-track/2} ${wheel_z}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.6" upper="0.6" effort="5.0" velocity="2.0"/>
  </joint>

  <!-- Front wheels (not driven here; can be driven too if desired) -->
  <link name="front_left_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="Black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder_y mass="0.25" radius="${wheel_radius}" length="${wheel_width}"/>
  </link>

  <joint name="front_left_wheel_joint" type="continuous">
    <parent link="front_left_steer_link"/>
    <child link="front_left_wheel_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <link name="front_right_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="Black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder_y mass="0.25" radius="${wheel_radius}" length="${wheel_width}"/>
  </link>

  <joint name="front_right_wheel_joint" type="continuous">
    <parent link="front_right_steer_link"/>
    <child link="front_right_wheel_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Gazebo Sim (Fortress / ign-gazebo6) system plugin configuration.
       This is consumed by sdformat_urdf when the model is spawned into Gazebo. -->
  <gazebo>
    <plugin
      filename="ignition-gazebo-ackermann-steering-system"
      name="gz::sim::systems::AckermannSteering">
      <left_joint>rear_left_wheel_joint</left_joint>
      <right_joint>rear_right_wheel_joint</right_joint>
      <left_steering_joint>front_left_steer_joint</left_steering_joint>
      <right_steering_joint>front_right_steer_joint</right_steering_joint>
      <kingpin_width>${track}</kingpin_width>
      <steering_limit>0.6</steering_limit>
      <wheel_base>${wheelbase}</wheel_base>
      <wheel_separation>${track}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <min_velocity>-2</min_velocity>
      <max_velocity>2</max_velocity>
      <min_acceleration>-3</min_acceleration>
      <max_acceleration>3</max_acceleration>
    </plugin>

    <plugin
      filename="ignition-gazebo-joint-state-publisher-system"
      name="gz::sim::systems::JointStatePublisher" />

    <plugin
      filename="ignition-gazebo-odometry-publisher-system"
      name="ignition::gazebo::systems::OdometryPublisher">
      <dimensions>3</dimensions>
      <odom_frame>odom</odom_frame>
      <robot_base_frame>base_footprint</robot_base_frame>
      <odom_publish_frequency>50</odom_publish_frequency>
    </plugin>
  </gazebo>

</robot>


